### ISSUE TITLE
Mitigated vulnerability data

### ISSUE THREAD

**Issue by danilansible** [packetchaos/ivan#2]
Hi there,

Thank you for the great work! It simplifies a lot compared to dealing directly with APIs.
When it gets data into the database, only two tables seem to be there keys and vulns.
Is the mitigated data missing from this?

**Comment by packetchaos** [comment]
Please for give me for the late response.  My alerts for this repo were turned off by accident.

I'm adding that as an option in the coming weeks.  Right now it pulls everything active.
